# ── Пулы моделей по роли ─────────────────────────────────────────────────────
MODEL_POOLS: dict[str, list[str]] = {
    "developer":        ["rnj-1:8b"],
    "reviewer":         ["rnj-1:8b"],
    "e2e_architect":    ["qwen3:latest"],
    "e2e_qa":           ["qwen3:latest"],
    "qa_runtime":       ["rnj-1:8b"],
    "business_analyst": ["qwen3:latest"],
    "system_analyst":   ["rnj-1:8b"],
    "architect":        ["rnj-1:8b"],
    "spec_reviewer":    ["qwen3:latest"],
    "test_generator":   ["rnj-1:8b"],
    "documenter":       ["qwen3:latest"],
    "devops_runtime":   ["qwen3:latest"],
    "arch_validator":   ["rnj-1:8b"],
    "supervisor":       ["qwen3:latest"],
    "self_reflect":     ["rnj-1:8b"],
    "contract_analyst": ["rnj-1:8b"],
    "a5_validator":     ["rnj-1:8b"],
}