# ── Пулы моделей по роли ─────────────────────────────────────────────────────
MODEL_POOLS: dict[str, list[str]] = {
    "developer":        ["deepseek-coder:6.7b"],
    "developer_patch":  ["deepseek-coder:6.7b"],
    "reviewer":         ["deepseek-coder:6.7b"],
    "e2e_architect":    ["qwen3:latest"],
    "e2e_qa":           ["qwen3:latest"],
    "qa_runtime":       ["deepseek-coder:6.7b"],
    "business_analyst": ["qwen3:latest"],
    "system_analyst":   ["deepseek-coder:6.7b"],
    "architect":        ["deepseek-coder:6.7b"],
    "spec_reviewer":    ["qwen3:latest"],
    "test_generator":   ["deepseek-coder:6.7b"],
    "documenter":       ["qwen3:latest"],
    "devops_runtime":   ["qwen3:latest"],
    "arch_validator":   ["deepseek-coder:6.7b"],
    "supervisor":       ["qwen3:latest"],
    "self_reflect":     ["deepseek-coder:6.7b"],
    "contract_analyst": ["deepseek-coder:6.7b"],
    "a5_validator":          ["deepseek-coder:6.7b"],
    "a5_business_reviewer":  ["qwen3:latest"],
    "a5_architect_reviewer": ["qwen3:latest"],
    "a5_contract_reviewer":  ["deepseek-coder:6.7b"],
}